import React, { useState } from "react";

import Head from 'next/head'
import styles from '../styles/Index.module.css'

import fire, { auth, db } from "../firebase";


//components
import Navbar from '../components/Navbar'
import Menu from '../components/Menu'
import EventCards from '../components/EventCards'

export default function Home() {
  const [showMenu, setShowMenu] = useState(false);
  console.log(auth.currentUser)
  return (
    <div className={styles.container}>
      <Head>
        <title>FOMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showMenu ? <Menu showMenu={showMenu} setShowMenu={setShowMenu} /> : null}
      <Navbar showMenu={showMenu} setShowMenu={setShowMenu} />
      {/* EVENT CARDS */}
      <EventCards />
      {/* BUTTONS */}



    </div>
  )
}
