import React, { useState, useEffect, useContext } from "react";

import Head from "next/head";
import styles from "../styles/Index.module.css";

import { UsersContext, DataContext } from "../context";

//components
import EventCards from "../components/EventCards";
import Filter from "../components/Filter";
import axios from 'axios'

export default function Home() {
  //context data
  const { showFilter} = useContext(UsersContext);
  const { userLocation, setUserLocation} = useContext(DataContext);



  return (
    <div className={styles.index__container} id="INDEX">
      <Head>
        <title>fomo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {/* EVENT CARDS & BUTTONS */}
      <EventCards />

      {/* FILTER */}
      {showFilter && <Filter  />}
       
      
    </div>
  );
}
